#Enable forge global version checking
versionCheck = true
splashscreen = true
#Default config path for servers
defaultConfigPath = "defaultconfigs"
#Disables Optimized DFU client-side - already disabled on servers
disableOptimizedDFU = true
maxThreads = -1

